/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.lang.String;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import person.Person;

/**
 *
 * @author Dell
 */
public class createPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createPersonJPanel
     */
    Person person;
    public createPersonJPanel(Person person) {
        initComponents();
        this.person = person;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namejLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        savejButton1 = new javax.swing.JButton();
        namejLabel2 = new javax.swing.JLabel();
        faxjLabel = new javax.swing.JLabel();
        certificatejLabel = new javax.swing.JLabel();
        telephonejLabel = new javax.swing.JLabel();
        dobjLabel = new javax.swing.JLabel();
        emailjLabel = new javax.swing.JLabel();
        ssnjLabel = new javax.swing.JLabel();
        mrnjLabel = new javax.swing.JLabel();
        hpbnjLabel = new javax.swing.JLabel();
        bankjLabel = new javax.swing.JLabel();
        namejLabel12 = new javax.swing.JLabel();
        bankjTextField = new javax.swing.JTextField();
        mrnjTextField = new javax.swing.JTextField();
        hpbnjTextField4 = new javax.swing.JTextField();
        faxjTextField5 = new javax.swing.JTextField();
        ssnjTextField6 = new javax.swing.JTextField();
        telephonejTextField7 = new javax.swing.JTextField();
        dobjTextField = new javax.swing.JTextField();
        emailjTextField = new javax.swing.JTextField();
        certificatejTextField = new javax.swing.JTextField();
        vehiclejTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        devicejTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        linkedinjTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ipjTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addressjTextField = new javax.swing.JTextField();
        picturejButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        namejLabel1.setText("Address :");

        nameField.setText("First Name");
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        namejLabel2.setText("Name :");

        faxjLabel.setText("Fax Number :");

        certificatejLabel.setText("Certificate/Licence Number :");

        telephonejLabel.setText("Telephone No : ");

        dobjLabel.setText("DOB :");

        emailjLabel.setText("Email address :");

        ssnjLabel.setText("SSN :");

        mrnjLabel.setText("Medical Record Number :");

        hpbnjLabel.setText("Health Plan Beneficiary Number :");

        bankjLabel.setText("Bank Account Number :");

        namejLabel12.setText("Vehicle identifiers and serial numbers including license plates :");

        bankjTextField.setText("Bank Account Number");
        bankjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankjTextFieldActionPerformed(evt);
            }
        });

        mrnjTextField.setText("Medical Record Number");
        mrnjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrnjTextFieldActionPerformed(evt);
            }
        });

        hpbnjTextField4.setText("Health Plan Beneficiary Number");
        hpbnjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpbnjTextField4ActionPerformed(evt);
            }
        });

        faxjTextField5.setText("FAX");
        faxjTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxjTextField5ActionPerformed(evt);
            }
        });

        ssnjTextField6.setText("Social Security Number");
        ssnjTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnjTextField6ActionPerformed(evt);
            }
        });

        telephonejTextField7.setText("Telephone Number");
        telephonejTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephonejTextField7ActionPerformed(evt);
            }
        });

        dobjTextField.setText("mm/dd/yyyy");
        dobjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobjTextFieldActionPerformed(evt);
            }
        });

        emailjTextField.setText("xyz@domain.com");
        emailjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextFieldActionPerformed(evt);
            }
        });

        certificatejTextField.setText("Certificate/Licence Number ");
        certificatejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificatejTextFieldActionPerformed(evt);
            }
        });

        vehiclejTextField2.setText("Vehicle identifiers and serial numbers including license plates");
        vehiclejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclejTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Device identifiers and serial numbers : ");

        devicejTextField3.setText("Device identifiers and serial numbers");
        devicejTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devicejTextField3ActionPerformed(evt);
            }
        });

        jLabel2.setText("LinkedIn :");

        linkedinjTextField4.setText("example@linkedin.com");
        linkedinjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkedinjTextField4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Internet Protocol Address :");

        ipjTextField5.setText("00.00.00.000");
        ipjTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipjTextField5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Biometric identifiers (i.e. retinal scan, fingerprints) : ");

        jLabel5.setText("Full face photos and comparable images :");

        addressjTextField.setText("Address");
        addressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressjTextFieldActionPerformed(evt);
            }
        });

        picturejButton1.setText("Take Picture");
        picturejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picturejButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Person Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(96, 96, 96)
                        .addComponent(picturejButton1))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(linkedinjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ipjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namejLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(namejLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(savejButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(faxjLabel)
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(telephonejLabel)
                                .addGap(78, 78, 78)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(faxjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(emailjLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(telephonejTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(ssnjLabel)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ssnjTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 25, Short.MAX_VALUE))))
                            .addComponent(dobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bankjLabel)
                                .addGap(18, 18, 18)
                                .addComponent(bankjTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(mrnjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mrnjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hpbnjLabel)
                            .addComponent(certificatejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(certificatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hpbnjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namejLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vehiclejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(devicejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dobjLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namejLabel1)
                            .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telephonejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephonejTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faxjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faxjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssnjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssnjTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrnjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrnjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpbnjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpbnjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certificatejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certificatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(devicejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(linkedinjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ipjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(picturejButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(savejButton1)
                .addGap(32, 32, 32))
        );

        certificatejLabel.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        // TODO add your handling code here:
        if (isSsnValid()== true){ 
            
            
        person.setAddress(addressjTextField.getText());
        person.setName(nameField.getText());
        person.setDob(dobjTextField.getText());
        person.setFax(faxjTextField5.getText());
        person.setSsn(ssnjTextField6.getText());
        person.setMedicalrnumber(mrnjTextField.getText());
        person.setVehicle(vehiclejTextField2.getText());
        person.setDevice(devicejTextField3.getText());
        person.setHealthplannumber(hpbnjTextField4.getText());
        person.setLinkedin(linkedinjTextField4.getText());
        person.setIpaddress(ipjTextField5.getText());
        person.setTelephone(telephonejTextField7.getText()); 
        person.setBankaccount(bankjTextField.getText());
        
        person.setLicencenumber(certificatejTextField.getText());
        person.setEmail(emailjTextField.getText());
        
        JOptionPane.showMessageDialog(this,"Person Information is saved !");
        }
        
        else 
        {
            JOptionPane.showMessageDialog(this,"Please enter valid Information!");
        }
        
               
        
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void dobjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobjTextFieldActionPerformed
        // TODO add your handling code here:
        person.setDob(dobjTextField.getText());
    }//GEN-LAST:event_dobjTextFieldActionPerformed

    private void faxjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxjTextField5ActionPerformed
        // TODO add your handling code here:
        person.setFax(faxjTextField5.getText());
    }//GEN-LAST:event_faxjTextField5ActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        person.setName(nameField.getText());
    }//GEN-LAST:event_nameFieldActionPerformed

    private void ssnjTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnjTextField6ActionPerformed
        // TODO add your handling code here:
        person.setSsn(ssnjTextField6.getText());
    }//GEN-LAST:event_ssnjTextField6ActionPerformed

    private void mrnjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrnjTextFieldActionPerformed
        // TODO add your handling code here:
        person.setMedicalrnumber(mrnjTextField.getText());
    }//GEN-LAST:event_mrnjTextFieldActionPerformed

    private void vehiclejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclejTextField2ActionPerformed
        // TODO add your handling code here:
        person.setVehicle(vehiclejTextField2.getText());
    }//GEN-LAST:event_vehiclejTextField2ActionPerformed

    private void devicejTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devicejTextField3ActionPerformed
        // TODO add your handling code here:
        person.setDevice(devicejTextField3.getText());
    }//GEN-LAST:event_devicejTextField3ActionPerformed

    private void hpbnjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpbnjTextField4ActionPerformed
        // TODO add your handling code here:
        person.setHealthplannumber(hpbnjTextField4.getText());
    }//GEN-LAST:event_hpbnjTextField4ActionPerformed

    private void linkedinjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkedinjTextField4ActionPerformed
        // TODO add your handling code here:
        person.setLinkedin(linkedinjTextField4.getText());
    }//GEN-LAST:event_linkedinjTextField4ActionPerformed

    private void ipjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipjTextField5ActionPerformed
        // TODO add your handling code here:
        person.setIpaddress(ipjTextField5.getText());
    }//GEN-LAST:event_ipjTextField5ActionPerformed

    private void certificatejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificatejTextFieldActionPerformed
        // TODO add your handling code here:
        
                person.setLicencenumber(certificatejTextField.getText());
    }//GEN-LAST:event_certificatejTextFieldActionPerformed

    private void telephonejTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephonejTextField7ActionPerformed
        // TODO add your handling code here:
        person.setTelephone(telephonejTextField7.getText());        
    }//GEN-LAST:event_telephonejTextField7ActionPerformed

    private void bankjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankjTextFieldActionPerformed
        // TODO add your handling code here:
        person.setBankaccount(bankjTextField.getText());
    }//GEN-LAST:event_bankjTextFieldActionPerformed

    private void addressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressjTextFieldActionPerformed
        // TODO add your handling code here:
        person.setAddress(addressjTextField.getText());
    }//GEN-LAST:event_addressjTextFieldActionPerformed

    private void emailjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextFieldActionPerformed
        // TODO add your handling code here:
        person.setEmail(emailjTextField.getText());
        
        
      
        
        
    }//GEN-LAST:event_emailjTextFieldActionPerformed

    private void picturejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picturejButton1ActionPerformed

    }//GEN-LAST:event_picturejButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjTextField;
    private javax.swing.JLabel bankjLabel;
    private javax.swing.JTextField bankjTextField;
    private javax.swing.JLabel certificatejLabel;
    private javax.swing.JTextField certificatejTextField;
    private javax.swing.JTextField devicejTextField3;
    private javax.swing.JLabel dobjLabel;
    private javax.swing.JTextField dobjTextField;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JLabel faxjLabel;
    private javax.swing.JTextField faxjTextField5;
    private javax.swing.JLabel hpbnjLabel;
    private javax.swing.JTextField hpbnjTextField4;
    private javax.swing.JTextField ipjTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField linkedinjTextField4;
    private javax.swing.JLabel mrnjLabel;
    private javax.swing.JTextField mrnjTextField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel namejLabel1;
    private javax.swing.JLabel namejLabel12;
    private javax.swing.JLabel namejLabel2;
    private javax.swing.JButton picturejButton1;
    private javax.swing.JButton savejButton1;
    private javax.swing.JLabel ssnjLabel;
    private javax.swing.JTextField ssnjTextField6;
    private javax.swing.JLabel telephonejLabel;
    private javax.swing.JTextField telephonejTextField7;
    private javax.swing.JTextField vehiclejTextField2;
    // End of variables declaration//GEN-END:variables

    private boolean isSsnValid() {
        String temp = ssnjTextField6.getText();
        if (temp.isEmpty() == true ){
            return false;
        } if(temp.length()!=9){
            return false;
        }else
        { return true;
        }
        
           }

   /* private boolean isEmailValid(String emailjTextField) {
      String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
      return emailjTextField.matches(regex); //To change body of generated methods, choose Tools | Templates.
    }*/
}
